### ISSUE TITLE
Add demo for `ConstraintLayout` feature minimum dimensions

### ISSUE THREAD

**Issue by noorejannat** [amardeshbd/android-constraint-layout-cheatsheet#29] opened 2018-05-06 20:16 UTC
### Minimum dimensions on ConstraintLayout
You can define minimum and maximum sizes for the ConstraintLayout itself:

android:minWidth set the minimum width for the layout
android:minHeight set the minimum height for the layout
android:maxWidth set the maximum width for the layout
android:maxHeight set the maximum height for the layout
Those minimum and maximum dimensions will be used by ConstraintLayout when its dimensions are set to WRAP_CONTENT.

**Comment by amardeshbd** [comment] 2019-04-13 12:47
Duplicate of #54

**Closed by amardeshbd** 2019-04-13 12:47 UTC
Labels: core, enhancement
